name: Given Verilog Code Runs Properly

on:
  push:
    branches:
      - main

jobs:
  autograder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Install Icarus Verilog
      - name: Install Icarus Verilog
        run: |
          sudo apt update
          sudo apt install -y iverilog

      # Step 3: Compile Verilog Code with predefined testbench
      - name: Compile Verilog Code
        run: |
          # Compile the code with the testbench
          iverilog -o simulation_output -s dummy_tb Lab_7_v_files/*.v Testbenches/*.v Modified/*.v

      # Step 4: Run Simulation and Capture Output
      - name: Run Simulation
        run: |
          # Run the compiled simulation and save the output to results.txt
          vvp simulation_output > results.txt

      # Step 5: Show Test Results in GitHub Actions Logs
      - name: Output Simulation Results
        run: |
          cat results.txt  # Display results in the Actions log
          
      # Step 6: Upload Results as an Artifact for Later Review
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.actor }}
          path: results.txt


      # Step 7: Check Simulation Results
      - name: Check Simulation Results
        run: |
          if grep -q "FAIL" results.txt; then
            echo "Simulation failed."
            exit 1
          else
            echo "Simulation passed."
          fi